// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoU5NOcMFW9B-Z5Q-cVmM5C2bmDcOOKLo',
    appId: '1:498061610472:web:d79c65f4b2efb09aca285d',
    messagingSenderId: '498061610472',
    projectId: 'eduapp-7cba3',
    authDomain: 'eduapp-7cba3.firebaseapp.com',
    storageBucket: 'eduapp-7cba3.appspot.com',
    measurementId: 'G-RNK7ZG9NV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-GvJQb65wPZUsdtCdHYCrLQhzHv0GoLc',
    appId: '1:498061610472:android:87e6d573ee32cd41ca285d',
    messagingSenderId: '498061610472',
    projectId: 'eduapp-7cba3',
    storageBucket: 'eduapp-7cba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd2EgEZmUe_-ioG0jCeiok_Z_1Ayl1Utw',
    appId: '1:498061610472:ios:3a2cb255be450337ca285d',
    messagingSenderId: '498061610472',
    projectId: 'eduapp-7cba3',
    storageBucket: 'eduapp-7cba3.appspot.com',
    iosBundleId: 'com.example.eduApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd2EgEZmUe_-ioG0jCeiok_Z_1Ayl1Utw',
    appId: '1:498061610472:ios:8067c77b5e3d3e30ca285d',
    messagingSenderId: '498061610472',
    projectId: 'eduapp-7cba3',
    storageBucket: 'eduapp-7cba3.appspot.com',
    iosBundleId: 'com.example.eduApp.RunnerTests',
  );
}
